server:
  port: 8761 # Puerto donde correrá el servidor Eureka

spring:
  application:
    name: eureka-server # Nombre del servidor Eureka

eureka:
  client:
    register-with-eureka: false # El servidor no se registra a sí mismo
    fetch-registry: false       # El servidor no busca otros registros
